services:
  - mongodb

language: node_js

node_js:
  - stable

branches:
  only:
    - master

install:
  - yarn install

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ];export TRAVIS_PULL=true; yarn test; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false"]; yarn test; fi'

after_success:
  - yarn run deploy
