version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb:/data/db
    restart: "unless-stopped"

  express:
    container_name: express
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./media:/server/media
    restart: "unless-stopped"
